### ISSUE TITLE
Minor bug: occasionally can't enter password when connecting to lt.net game

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#785] opened 2021-12-24 08:13 UTC
Sometimes when I try to connect to a LT game, I click "Connect", get a message "Please enter your password", the field is ungreyed and cursor appears, only for the field to be greyed again and cursor to disappear a moment later.

Happens maybe 20% of the time, retrying usually solves the problem.

Windows version 3.0.20211008.

![image](https://user-images.githubusercontent.com/25233743/147333122-83fdd573-aade-4b4c-8b70-b235fb63ffc3.png)

**Comment by lmoureaux** [comment] 2022-01-01 17:54
I recall having this issue in the Aviation game. Should dump network packets and state changes.

**Comment by jwrober** [comment] 2022-01-02 20:19
Might be a duplicate of #540

**Comment by Corbeau-1** [comment] 2022-01-02 22:52
> Might be a duplicate of #540

In some cases a password prompt appeared and then disappeared a moment later. Can't say for all.

**Comment by lmoureaux** [comment] 2022-08-22 00:25
Couldn't repro on a quick test today with LT73Avi and bde58765f0f630f9da6dc205f281ec06472469ec.

**Comment by lmoureaux** [comment] 2023-01-06 02:03
@hugomflavio and @daavko reported seeing this issue with LT76. Still unable to reproduce on my end.

**Comment by lmoureaux** [comment] 2023-01-06 02:24
Potentially caused by a slow metaserver response:

> So... if you manage to click "Connect" between "request sent" and "response received", and the game server gets you the "hey, auth yourself" packet in that timeframe as well, the game technically switches to "input password" mode. But then, when the metaserver response is received, the dialog gets switched back to "input login" mode, because that's part of switching from main page to connect page

**Closed** 2023-01-08 00:54 UTC
Labels: bug, question, gui
