### ISSUE TITLE
City dialog reverts to upper left of the screen on minimize-maximize

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#440] opened 2021-04-16 21:49 UTC
Open the city dialog on any city. Leave city dialog open. Minimize the client to the task bar. Maximize the client to show it again and you get this

![image](https://user-images.githubusercontent.com/23037938/115087385-ac3e8a80-9ed3-11eb-9b1e-07846293de39.png)

**Comment by pranavtifr** [comment] 2021-04-17 15:53
Is this the recent version ? Duplicate of #232  #377  and should have been closed by #404.

**Comment by pranavtifr** [comment] 2021-04-17 22:29
Okay. Just played a game from https://github.com/longturn/freeciv21/commit/ba42a6961e2044ef650c2d0f9b301fd798a4d354. 
Can confirm that the issue still persists.

**Comment by jwrober** [comment] 2021-04-18 01:07
Yea you figured it out already. I compiled from master yesterday afternoon.

**Closed** 2021-05-06 08:42 UTC
Labels: bug
