### ISSUE TITLE
Assertion nullptr != src failed

### ISSUE THREAD

**Issue by wsfsbvchr** [longturn/freeciv21#2046] opened 2023-10-19 10:43 UTC
**Describe the bug**
Assertion nullptr != src failed is shown twice in freeciv21-client's output.

**To Reproduce**
1. Start the game
2. Connect to game
3. Quit game
4. See error in command line

**Expected behavior**
I'd expect not to see requests to report messages at issue trackers.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: freeciv21-client 3.0.102624.1-patch
 - Ruleset/Longturn game (if applicable): https://longturn.net/game/Suomipeli2023b/

**Additional context**
Full freeciv21-client output of this session:

```
[critical] freeciv21-client - warning: already have a sprite for "b.apollo_program".
[critical] freeciv21-client - warning: already have a sprite for "b.asmiths_trading_co".
[critical] freeciv21-client - warning: already have a sprite for "b.colossus".
[critical] freeciv21-client - warning: already have a sprite for "b.copernicus_observatory".
[critical] freeciv21-client - warning: already have a sprite for "b.cure_for_cancer".
[critical] freeciv21-client - warning: already have a sprite for "b.darwins_voyage".
[critical] freeciv21-client - warning: already have a sprite for "b.ecclesiastical_palace".
[critical] freeciv21-client - warning: already have a sprite for "b.eiffel_tower".
[critical] freeciv21-client - warning: already have a sprite for "b.great_library".
[critical] freeciv21-client - warning: already have a sprite for "b.great_wall".
[critical] freeciv21-client - warning: already have a sprite for "b.hanging_gardens".
[critical] freeciv21-client - warning: already have a sprite for "b.hoover_dam".
[critical] freeciv21-client - warning: already have a sprite for "b.internet".
[critical] freeciv21-client - warning: already have a sprite for "b.isaac_newtons_college".
[critical] freeciv21-client - warning: already have a sprite for "b.js_bachs_cathedral".
[critical] freeciv21-client - warning: already have a sprite for "b.king_richards_crusade".
[critical] freeciv21-client - warning: already have a sprite for "b.leonardos_workshop".
[critical] freeciv21-client - warning: already have a sprite for "b.lighthouse".
[critical] freeciv21-client - warning: already have a sprite for "b.magellans_expedition".
[critical] freeciv21-client - warning: already have a sprite for "b.manhattan_project".
[critical] freeciv21-client - warning: already have a sprite for "b.marco_polos_embassy".
[critical] freeciv21-client - warning: already have a sprite for "b.mausoleum".
[critical] freeciv21-client - warning: already have a sprite for "b.michelangelos_chapel".
[critical] freeciv21-client - warning: already have a sprite for "b.oracle".
[critical] freeciv21-client - warning: already have a sprite for "b.palace".
[critical] freeciv21-client - warning: already have a sprite for "b.pyramids".
[critical] freeciv21-client - warning: already have a sprite for "b.seti_program".
[critical] freeciv21-client - warning: already have a sprite for "b.shakespeares_theatre".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_liberty".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_zeus".
[critical] freeciv21-client - warning: already have a sprite for "b.sun_tzus_war_academy".
[critical] freeciv21-client - warning: already have a sprite for "b.temple_of_artemis".
[critical] freeciv21-client - warning: already have a sprite for "b.united_nations".
[critical] freeciv21-client - warning: already have a sprite for "b.womens_suffrage".
[critical] freeciv21-client - warning: already have a sprite for "b.apollo_program".
[critical] freeciv21-client - warning: already have a sprite for "b.asmiths_trading_co".
[critical] freeciv21-client - warning: already have a sprite for "b.colossus".
[critical] freeciv21-client - warning: already have a sprite for "b.copernicus_observatory".
[critical] freeciv21-client - warning: already have a sprite for "b.cure_for_cancer".
[critical] freeciv21-client - warning: already have a sprite for "b.darwins_voyage".
[critical] freeciv21-client - warning: already have a sprite for "b.ecclesiastical_palace".
[critical] freeciv21-client - warning: already have a sprite for "b.eiffel_tower".
[critical] freeciv21-client - warning: already have a sprite for "b.great_library".
[critical] freeciv21-client - warning: already have a sprite for "b.great_wall".
[critical] freeciv21-client - warning: already have a sprite for "b.hanging_gardens".
[critical] freeciv21-client - warning: already have a sprite for "b.hoover_dam".
[critical] freeciv21-client - warning: already have a sprite for "b.internet".
[critical] freeciv21-client - warning: already have a sprite for "b.isaac_newtons_college".
[critical] freeciv21-client - warning: already have a sprite for "b.js_bachs_cathedral".
[critical] freeciv21-client - warning: already have a sprite for "b.king_richards_crusade".
[critical] freeciv21-client - warning: already have a sprite for "b.leonardos_workshop".
[critical] freeciv21-client - warning: already have a sprite for "b.lighthouse".
[critical] freeciv21-client - warning: already have a sprite for "b.magellans_expedition".
[critical] freeciv21-client - warning: already have a sprite for "b.manhattan_project".
[critical] freeciv21-client - warning: already have a sprite for "b.marco_polos_embassy".
[critical] freeciv21-client - warning: already have a sprite for "b.mausoleum".
[critical] freeciv21-client - warning: already have a sprite for "b.michelangelos_chapel".
[critical] freeciv21-client - warning: already have a sprite for "b.oracle".
[critical] freeciv21-client - warning: already have a sprite for "b.palace".
[critical] freeciv21-client - warning: already have a sprite for "b.pyramids".
[critical] freeciv21-client - warning: already have a sprite for "b.seti_program".
[critical] freeciv21-client - warning: already have a sprite for "b.shakespeares_theatre".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_liberty".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_zeus".
[critical] freeciv21-client - warning: already have a sprite for "b.sun_tzus_war_academy".
[critical] freeciv21-client - warning: already have a sprite for "b.temple_of_artemis".
[critical] freeciv21-client - warning: already have a sprite for "b.united_nations".
[critical] freeciv21-client - warning: already have a sprite for "b.womens_suffrage".
[critical] freeciv21-client - warning: already have a sprite for "b.apollo_program".
[critical] freeciv21-client - warning: already have a sprite for "b.asmiths_trading_co".
[critical] freeciv21-client - warning: already have a sprite for "b.colossus".
[critical] freeciv21-client - warning: already have a sprite for "b.copernicus_observatory".
[critical] freeciv21-client - warning: already have a sprite for "b.cure_for_cancer".
[critical] freeciv21-client - warning: already have a sprite for "b.darwins_voyage".
[critical] freeciv21-client - warning: already have a sprite for "b.ecclesiastical_palace".
[critical] freeciv21-client - warning: already have a sprite for "b.eiffel_tower".
[critical] freeciv21-client - warning: already have a sprite for "b.great_library".
[critical] freeciv21-client - warning: already have a sprite for "b.great_wall".
[critical] freeciv21-client - warning: already have a sprite for "b.hanging_gardens".
[critical] freeciv21-client - warning: already have a sprite for "b.hoover_dam".
[critical] freeciv21-client - warning: already have a sprite for "b.internet".
[critical] freeciv21-client - warning: already have a sprite for "b.isaac_newtons_college".
[critical] freeciv21-client - warning: already have a sprite for "b.js_bachs_cathedral".
[critical] freeciv21-client - warning: already have a sprite for "b.king_richards_crusade".
[critical] freeciv21-client - warning: already have a sprite for "b.leonardos_workshop".
[critical] freeciv21-client - warning: already have a sprite for "b.lighthouse".
[critical] freeciv21-client - warning: already have a sprite for "b.magellans_expedition".
[critical] freeciv21-client - warning: already have a sprite for "b.manhattan_project".
[critical] freeciv21-client - warning: already have a sprite for "b.marco_polos_embassy".
[critical] freeciv21-client - warning: already have a sprite for "b.mausoleum".
[critical] freeciv21-client - warning: already have a sprite for "b.michelangelos_chapel".
[critical] freeciv21-client - warning: already have a sprite for "b.oracle".
[critical] freeciv21-client - warning: already have a sprite for "b.palace".
[critical] freeciv21-client - warning: already have a sprite for "b.pyramids".
[critical] freeciv21-client - warning: already have a sprite for "b.seti_program".
[critical] freeciv21-client - warning: already have a sprite for "b.shakespeares_theatre".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_liberty".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_zeus".
[critical] freeciv21-client - warning: already have a sprite for "b.sun_tzus_war_academy".
[critical] freeciv21-client - warning: already have a sprite for "b.temple_of_artemis".
[critical] freeciv21-client - warning: already have a sprite for "b.united_nations".
[critical] freeciv21-client - warning: already have a sprite for "b.womens_suffrage".
[critical] freeciv21-client - warning: already have a sprite for "b.apollo_program".
[critical] freeciv21-client - warning: already have a sprite for "b.asmiths_trading_co".
[critical] freeciv21-client - warning: already have a sprite for "b.colossus".
[critical] freeciv21-client - warning: already have a sprite for "b.copernicus_observatory".
[critical] freeciv21-client - warning: already have a sprite for "b.cure_for_cancer".
[critical] freeciv21-client - warning: already have a sprite for "b.darwins_voyage".
[critical] freeciv21-client - warning: already have a sprite for "b.ecclesiastical_palace".
[critical] freeciv21-client - warning: already have a sprite for "b.eiffel_tower".
[critical] freeciv21-client - warning: already have a sprite for "b.great_library".
[critical] freeciv21-client - warning: already have a sprite for "b.great_wall".
[critical] freeciv21-client - warning: already have a sprite for "b.hanging_gardens".
[critical] freeciv21-client - warning: already have a sprite for "b.hoover_dam".
[critical] freeciv21-client - warning: already have a sprite for "b.internet".
[critical] freeciv21-client - warning: already have a sprite for "b.isaac_newtons_college".
[critical] freeciv21-client - warning: already have a sprite for "b.js_bachs_cathedral".
[critical] freeciv21-client - warning: already have a sprite for "b.king_richards_crusade".
[critical] freeciv21-client - warning: already have a sprite for "b.leonardos_workshop".
[critical] freeciv21-client - warning: already have a sprite for "b.lighthouse".
[critical] freeciv21-client - warning: already have a sprite for "b.magellans_expedition".
[critical] freeciv21-client - warning: already have a sprite for "b.manhattan_project".
[critical] freeciv21-client - warning: already have a sprite for "b.marco_polos_embassy".
[critical] freeciv21-client - warning: already have a sprite for "b.mausoleum".
[critical] freeciv21-client - warning: already have a sprite for "b.michelangelos_chapel".
[critical] freeciv21-client - warning: already have a sprite for "b.oracle".
[critical] freeciv21-client - warning: already have a sprite for "b.palace".
[critical] freeciv21-client - warning: already have a sprite for "b.pyramids".
[critical] freeciv21-client - warning: already have a sprite for "b.seti_program".
[critical] freeciv21-client - warning: already have a sprite for "b.shakespeares_theatre".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_liberty".
[critical] freeciv21-client - warning: already have a sprite for "b.statue_of_zeus".
[critical] freeciv21-client - warning: already have a sprite for "b.sun_tzus_war_academy".
[critical] freeciv21-client - warning: already have a sprite for "b.temple_of_artemis".
[critical] freeciv21-client - warning: already have a sprite for "b.united_nations".
[critical] freeciv21-client - warning: already have a sprite for "b.womens_suffrage".
[warning] freeciv21-client - libpng warning: iCCP: known incorrect sRGB profile
[info] freeciv21-client - Loading tileset "amplio2".
[critical] freeciv21-client - Assertion nullptr != src failed
[critical] freeciv21-client - Please report this message at https://github.com/longturn/freeciv21/issues
[critical] freeciv21-client - Assertion nullptr != src failed
[critical] freeciv21-client - Please report this message at https://github.com/longturn/freeciv21/issues
[critical] freeciv21-client - Option type OT_STRING (2) not supported for 'nationset'.
[critical] freeciv21-client - Option type OT_BITWISE (4) not supported for 'airliftingstyle'.
[critical] freeciv21-client - Option type OT_STRING (2) not supported for 'allowtake'.
[critical] freeciv21-client - Option type OT_BITWISE (4) not supported for 'revealmap'.
[critical] freeciv21-client - Option type OT_BITWISE (4) not supported for 'unitwaittime_style'.
```

**Comment by lmoureaux** [comment] 2023-10-19 13:16
Thanks for reporting! This is a duplicate of #2032

**Closed** 2023-10-19 13:16 UTC
Labels: bug, Untriaged
