### ISSUE TITLE
Client bug: can't see all specialists in City window (F4), only Entertainers

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#794] opened 2021-12-31 11:19 UTC
... and those you can see those twice! (See pic)

Reproduce: open City window (F4), right-click to select columns you want to see, check the beginning of the list.

WHat should be there: 
Specialists: Entertainers
Specialists: Scientists
Specialists: Taxman
Specialists: All (E/S/T)

What is there:
![image](https://user-images.githubusercontent.com/25233743/147820585-9f8b63fb-b432-4e58-8c99-a6c8d51799fd.png)

**Comment by lmoureaux** [comment] 2022-01-01 17:48
I can't reproduce with the `classic` ruleset.

**Comment by Corbeau-1** [comment] 2022-01-02 13:05
Gh... I'm an idiot. Can we delete this?

**Comment by lmoureaux** [comment] 2022-01-02 15:36
Closing. For my own education, can you explain the reason?

**Closed by lmoureaux** 2022-01-02 15:36 UTC
Labels: bug, question, client

**Comment by Corbeau-1** [comment] 2022-01-02 17:24
No.

Delet dis.
