### ISSUE TITLE
Ability to "undo" actions

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#2397] opened 2024-09-27 21:39 UTC
**Is your feature request related to a problem? Please describe.**
This requires #2395. If the server logs every single action, then it should be possible to roll-back said actions.

**Describe the solution you'd like**
Give users with hack-level command access (or make a new access level for game admins) the power to undo a certain set of actions. Akin to Github's capacity to roll back on commits :)

**Describe alternatives you've considered**
Give game admins the ability to edit the current state of the game freely. This seems much harder to do.

**Comment by jwrober** [comment] 2024-10-06 23:26
Interesting idea. I'm more in favor of just going to a prior save as we do save often when playing LT games. I anticipate this will require a change in network protocol, especially if game admins use the client to issue commands to the server via chat line.

**Comment by hugomflavio** [comment] 2024-10-09 21:08
Going back to the nearest save doesn't always work. In the RTS case, going back to the nearest save punishes both the offender and the victim. Undoing only up to the point where the RTS happened is what is needed. Otherwise, dozens (sometimes hundreds) of moves may get undone (including for third party players).

**Comment by jwrober** [comment] 2024-10-09 22:24
We will need a much more stringent and followed RTS/non-RTS policy by game admins for this to work IRL. I think its better to have game admins determine what the rules are before a game starts and what the consequences are of non-compliance.

**Comment by hugomflavio** [comment] 2024-10-09 22:29
I can't make the consequences if the mechanisms to implement them don't exist. The idea is fairly simple. If RTS is reported, the game is paused and checked. If RTS happened, the moves are undone up to (and including) the RTS move. Details on what is RTS and on other consequences can be discussed in detail; this issue only addresses the basic mechanism of undoing the damage.

**Comment by hugomflavio** [comment] 2024-10-09 22:35
Being able to undo only certain events would be even better (e.g. if another player was moving elsewhere around the world, don't undo that).

**Comment by lmoureaux** [comment] 2024-10-10 10:51
I think you basically want #580

**Comment by hugomflavio** [comment] 2024-10-10 10:57
I mean, yes, that would work too, but that seems harder? 😅 Though it would be very useful even for further development.

**Comment by lmoureaux** [comment] 2024-10-10 18:09
The editor only needs UI work, undoing would in addition require saving everything and code to revert specific actions (keeping in mind that Lua scripts can do basically anything).

**Comment by hugomflavio** [comment] 2024-10-10 18:10
sold on the editor :D

**Comment by lmoureaux** [comment] 2024-10-10 18:13
ok to close as dup of #580 then?

**Comment by hugomflavio** [comment] 2024-10-10 18:35
heh, not quite a duplicate of the editor; this is a different thing. But the editor does what I need if paired with detailed logs of every action that happened in the server over time. So, could be closed for now if it is not of interest.

**Comment by lmoureaux** [comment] 2024-10-10 18:55
When a feature request proposes a specific solution to some problem, solving the problem is what really matters. Therefore the issue gets closed if another feature solving the same problem is implemented or planned. This prevents cluttering the issue tracker with feature requests solving problems that already have a solution.

I'm closing this as duplicate, we can obviously reopen if there is another use case.

**Closed by lmoureaux** 2024-10-10 18:55 UTC
Labels: enhancement, changes-network-protocol, server
