### ISSUE TITLE
It's possible to move the map while the city dialog is open

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1093] opened 2022-07-07 21:17 UTC
**Describe the bug**
When the city dialog is open, it's still possible to move the map by right-clicking. It probably shouldn't be, since the point of the city dialog is to focus on the city.

**To Reproduce**
1. Open a city dialog
2. Right-click anywhere on the visible map

**Expected behavior**
It should be locked and centered to the city.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by pranavtifr** [comment] 2022-07-07 22:02
I'm not sure I'd consider this a bug! Just like we can select a unit and move around the map, it should be possible to select the city and move around the map. And it becomes even more relevant when we unify unit and city interfaces later.

**Comment by daavko** [comment] 2022-07-07 22:12
I did look whether this has been reported before, looks like I didn't search hard enough. This is a duplicate of #566, which was closed as `wontfix`. I disagree with that, because a city view is for viewing the city and moving the map is unexpected, but I'll leave it at that. This issue can be closed as a duplicate.

**Comment by lmoureaux** [comment] 2022-07-07 22:25
How would you handle [this situation](https://github.com/longturn/freeciv21/issues/566#issuecomment-973329152)?

**Comment by jwrober** [comment] 2022-07-13 19:21
Duplicate of #566 , closing as won't fix as its expected at this time.

**Closed by jwrober** 2022-07-13 19:21 UTC
Labels: bug, duplicate, wontfix, client
