### ISSUE TITLE
Executable files don't run on double-click on linux

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#354] opened 2021-03-21 18:27 UTC
Get this message on my Linux Mint (Ubuntu) Laptop

![image](https://user-images.githubusercontent.com/23037938/111916458-010ff200-8a49-11eb-9799-8e1375b5a038.png)

Same way on Qt client with classic Freeciv. However the other clients show a "gear" icon in the middle and will run with a double click.

![image](https://user-images.githubusercontent.com/23037938/111916499-36b4db00-8a49-11eb-9282-d052ea115248.png)

**Comment by lmoureaux** [comment] 2021-03-21 20:38
Can you show the properties dialog for `freeciv-qt`? In particular, what's the detected MIME type and is the executable bit set?

This might be a Nautilus bug. I just tested with Dolphin (Kde) and couldn't reproduce. Can you try with PCManFM (LXDE), Thunar (XFCE) or Dolphin?

**Comment by jwrober** [comment] 2021-03-22 00:04
Dolphin thinks its a library?
![image](https://user-images.githubusercontent.com/23037938/111925670-d0937c80-8a77-11eb-81d1-b22f894332ef.png)
![image](https://user-images.githubusercontent.com/23037938/111925699-e5701000-8a77-11eb-8dca-c4ce790d7def.png)

```
~/Install/freeciv21-test/bin$ ls -l
total 36832
-rwxr-xr-x 1 jwrober jwrober 6318152 Mar 12 16:51 freeciv-manual
-rwxr-xr-x 1 jwrober jwrober 2336088 Mar 12 16:51 freeciv-modpack
-rwxr-xr-x 1 jwrober jwrober 2405424 Mar 12 16:51 freeciv-modpack-qt
-rwxr-xr-x 1 jwrober jwrober 7546512 Mar 12 16:51 freeciv-qt
-rwxr-xr-x 1 jwrober jwrober 6716656 Mar 12 16:52 freeciv-ruledit
-rwxr-xr-x 1 jwrober jwrober 6211152 Mar 12 16:51 freeciv-ruleup
-rwxr-xr-x 1 jwrober jwrober 6164768 Mar 12 16:51 freeciv-server
```

fc2.6.3 as comparison
![image](https://user-images.githubusercontent.com/23037938/111925721-ffa9ee00-8a77-11eb-9dfe-e96d6ecc5437.png)
![image](https://user-images.githubusercontent.com/23037938/111925735-12242780-8a78-11eb-96b1-cdbb56c52150.png)

```
~/Install/freeciv-263/bin$ ls -l
total 88680
-rwxr-xr-x 1 jwrober jwrober 10802120 Jan  5 16:51 freeciv-gtk2
-rwxr-xr-x 1 jwrober jwrober 10690104 Jan  5 16:51 freeciv-gtk3
-rwxr-xr-x 1 jwrober jwrober 10640832 Jan  5 16:51 freeciv-gtk3.22
-rwxr-xr-x 1 jwrober jwrober   637040 Jan  5 16:51 freeciv-manual
-rwxr-xr-x 1 jwrober jwrober   171496 Jan  5 16:51 freeciv-mp-gtk3
-rwxr-xr-x 1 jwrober jwrober 36575776 Jan  5 16:51 freeciv-qt
-rwxr-xr-x 1 jwrober jwrober  4242184 Jan  5 16:51 freeciv-ruledit
-rwxr-xr-x 1 jwrober jwrober 10225464 Jan  5 16:51 freeciv-sdl2
-rwxr-xr-x 1 jwrober jwrober    87520 Jan  5 16:51 freeciv-server
-rwxr-xr-x 1 jwrober jwrober  6709216 Jan  5 16:51 freeciv-stub
```

**Comment by lmoureaux** [comment] 2021-03-22 00:17
Looks like a `shared-mime-info` bug. Arch Linux:
```
freeciv21 $ file --mime-type build/install/bin/*
build/install/bin/freeciv-manual:     application/x-pie-executable
build/install/bin/freeciv-modpack:    application/x-pie-executable
build/install/bin/freeciv-modpack-qt: application/x-pie-executable
build/install/bin/freeciv-qt:         application/x-pie-executable
build/install/bin/freeciv-ruledit:    application/x-pie-executable
build/install/bin/freeciv-ruleup:     application/x-pie-executable
build/install/bin/freeciv-server:     application/x-pie-executable
```

**Comment by jwrober** [comment] 2021-03-22 00:44
fc

```
~/Install/freeciv-263/bin$ file --mime-type *
freeciv-gtk2:    application/x-executable
freeciv-gtk3:    application/x-executable
freeciv-gtk3.22: application/x-executable
freeciv-manual:  application/x-executable
freeciv-mp-gtk3: application/x-executable
freeciv-qt:      application/x-sharedlib
freeciv-ruledit: application/x-sharedlib
freeciv-sdl2:    application/x-executable
freeciv-server:  application/x-executable
freeciv-stub:    application/x-executable
```
fc21
```
~/Install/freeciv21-test/bin$ file --mime-type *
freeciv-manual:     application/x-sharedlib
freeciv-modpack:    application/x-sharedlib
freeciv-modpack-qt: application/x-sharedlib
freeciv-qt:         application/x-sharedlib
freeciv-ruledit:    application/x-sharedlib
freeciv-ruleup:     application/x-sharedlib
freeciv-server:     application/x-sharedlib
```

**Comment by lmoureaux** [comment] 2021-03-22 00:48
What does it say for apps built by the distro? Especially ones linking to Qt, eg Dolphin. You can try `file --mime-type /usr/bin/* | grep x-sharedlib`.

**Comment by jwrober** [comment] 2021-03-22 18:30
Even some Gtk apps show the `x-sharelib`. One example is `/usr/bin/gnome-calendar`. The sample command produces a long list of files.

```
file --mime-type /usr/bin/* | grep x-executable
/usr/bin/python3.8:                                       application/x-executable
/usr/bin/x86_64-linux-gnu-cpp-9:                          application/x-executable
/usr/bin/x86_64-linux-gnu-g++-9:                          application/x-executable
/usr/bin/x86_64-linux-gnu-gcc-9:                          application/x-executable
/usr/bin/x86_64-linux-gnu-gcc-ar-9:                       application/x-executable
/usr/bin/x86_64-linux-gnu-gcc-nm-9:                       application/x-executable
/usr/bin/x86_64-linux-gnu-gcc-ranlib-9:                   application/x-executable
/usr/bin/x86_64-linux-gnu-gcov-9:                         application/x-executable
/usr/bin/x86_64-linux-gnu-gcov-dump-9:                    application/x-executable
/usr/bin/x86_64-linux-gnu-gcov-tool-9:                    application/x-executable
```

```
file --mime-type /usr/bin/* | grep x-sharedlib | wc -l
965
```

**Comment by lmoureaux** [comment] 2021-03-22 18:40
Closing as upstream `shared-mime-info` [issue#11](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/11).

**Closed by lmoureaux** 2021-03-22 18:40 UTC
Labels: bug
