### ISSUE TITLE
Assertion pplayer == client_player() fails

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#457] opened 2021-05-02 12:13 UTC
`[critical] freeciv-qt (unknown:0) - Assertion pplayer == client_player() failed`

This came up in my testgame with Soundnfury. I wasnt able to replicate it in my local game even with the aviation ruleset, but I suspect it happens when the server closes the game with the client still running.

**Comment by lmoureaux** [comment] 2022-08-06 00:48
> I suspect it happens when the server closes the game with the client still running.

Didn't get this when doing `/quit` or hard killing my local server.

The assertion is in `client_plr_tile_city_id_get` in `client_main.cpp`. For it to fire, we need to be calculating information about an action against a city (whether it is possible, `is_action_possible`) for a unit that is not owned by the current player. Of course it could also happen if one of the pointers is garbage.

**Comment by lmoureaux** [comment] 2022-08-06 14:53
Couldn't reproduce.

**Comment by jwrober** [comment] 2022-08-06 14:58
I can't either. I think we may have fixed it along the way with all the refactoring being done. I say we close this issue and if we can reproduce later we open a new one with better reproducible steps documented.

**Comment by lmoureaux** [comment] 2022-08-06 15:52
Just saw it, trying to reproduce...
```
[critical] freeciv21-client (/home/louis/freeciv/freeciv21/client/client_main.cpp:1240) - Assertion pplayer == client_player() failed
```

**Comment by lmoureaux** [comment] 2022-08-06 15:53
Repro steps:

* Open city dialog
* Close city dialog
* /observe yourself

**Comment by lmoureaux** [comment] 2022-08-06 17:58
```
#0  fc_assert_handle_failure(char const*, char const*, int, char const*, QString const&)
    (condition=0x5555555d84df <QByteArray::constData() const+31> "\311Ð\363\017\036\372UH\211\345H\203\354\020H\211}\370H\213E\370H\213", file=0x7fffffffc170 "E", line=21845, function=0x7fffffffc170 "E", message="") at /home/louis/freeciv/freeciv21/utility/log.cpp:226
#1  0x0000555555616fd5 in client_plr_tile_city_id_get(tile const*, player const*) (ptile=0x55555a1f33b0, pplayer=0x55555a0dae20) at /home/louis/freeciv/freeciv21/client/client_main.cpp:1240
#2  0x0000555555808e55 in is_action_possible(action_id, player const*, city const*, impr_type const*, tile const*, unit const*, unit_type const*, output_type const*, specialist const*, player const*, city const*, impr_type const*, tile const*, unit const*, unit_type const*, output_type const*, specialist const*, extra_type const*, bool, city const*)
    (wanted_action=43, actor_player=0x55555a0dae20, actor_city=0x55555a3b7ab0, actor_building=0x0, actor_tile=0x55555a1f33b0, actor_unit=0x55555accae00, actor_unittype=0x555555ca9540 <unit_types+18304>, actor_output=0x0, actor_specialist=0x0, target_player=0x55555a0dae20, target_city=0x55555a3b7ab0, target_building=0x555555c5c340 <improvement_types>, target_tile=0x55555a1f33b0, target_unit=0x0, target_unittype=0x0, target_output=0x0, target_specialist=0x0, target_extra=0x0, omniscient=false, homecity=0x55555a3b7ab0)
    at /home/louis/freeciv/freeciv21/common/actions.cpp:3037
#3  0x000055555580ceec in action_prob(action_id, player const*, city const*, impr_type const*, tile const*, unit const*, unit_type const*, output_type const*, specialist const*, city const*, player const*, city const*, impr_type const*, tile const*, unit const*, unit_type const*, output_type const*, specialist const*, extra_type const*)
    (wanted_action=43, actor_player=0x55555a0dae20, actor_city=0x55555a3b7ab0, actor_building=0x0, actor_tile=0x55555a1f33b0, actor_unit=0x55555accae00, actor_unittype_p=0x0, actor_output=0x--Type <RET> for more, q to quit, c to continue without paging--
0, actor_specialist=0x0, actor_home=0x55555a3b7ab0, target_player=0x55555a0dae20, target_city=0x55555a3b7ab0, target_building=0x555555c5c340 <improvement_types>, target_tile=0x55555a1f33b0, target_unit=0x0, target_unittype_p=0x0, target_output=0x0, target_specialist=0x0, target_extra=0x0) at /home/louis/freeciv/freeciv21/common/actions.cpp:4482
#4  0x000055555580d833 in action_prob_vs_city_full(unit const*, city const*, tile const*, action_id, city const*)
    (actor_unit=0x55555accae00, actor_home=0x55555a3b7ab0, actor_tile=0x55555a1f33b0, act_id=43, target_city=0x55555a3b7ab0) at /home/louis/freeciv/freeciv21/common/actions.cpp:4802
#5  0x000055555580d8fc in action_prob_vs_city(unit const*, int, city const*) (actor_unit=0x55555accae00, act_id=43, target_city=0x55555a3b7ab0)
    at /home/louis/freeciv/freeciv21/common/actions.cpp:4815
#6  0x00005555558b26f7 in can_unit_change_homecity_to(unit const*, city const*) (punit=0x55555accae00, pcity=0x55555a3b7ab0) at /home/louis/freeciv/freeciv21/common/unit.cpp:423
#7  0x000055555568a25b in unit_actions::update_actions() (this=0x5555566f7e10) at /home/louis/freeciv/freeciv21/client/hudwidget.cpp:1048
#8  0x0000555555687ec9 in hud_units::update_actions(unit_list*) (this=0x555556703bb0, punits=0x0) at /home/louis/freeciv/freeciv21/client/hudwidget.cpp:774
#9  0x00005555556b0b33 in real_menus_update() () at /home/louis/freeciv/freeciv21/client/menu.cpp:124
#10 0x00005555557a4135 in menus_update_callback(void*) (data=0x0) at /home/louis/freeciv/freeciv21/client/update_queue.cpp:408
```

**Closed** 2022-08-08 21:02 UTC
Labels: bug, client
